name: UI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Elm App
      run: npm install -g create-elm-app
    - name: Npm dependencies
      run: npm install -g elm@latest-0.19.1
    - name: Build Prod
      run: elm-app build
    - name: Authenticate into Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        export_default_credentials: true
    - name: Sync with GCP
      run: "gsutil -m rsync -R ./build gs://bible.jholmestech.com"
